"""
Debian preseed-based ISO builder.

Builds a custom ISO that uses debian-installer's preseed to do an unattended
install. The preseed.cfg goes at the ISO root, and we patch grub.cfg (UEFI)
and isolinux/menu.cfg (BIOS) to add an autoinstall entry.
"""

from pathlib import Path
from typing import Dict, List, Tuple

from core import iso, postinstall, ui
from .base import Builder


GRUB_AUTOINSTALL_ENTRY = """menuentry "Debian Autoinstall (Wipes Disk)" {
    set gfxpayload=keep
    linux    /install.amd/vmlinuz auto=true priority=critical preseed/file=/cdrom/preseed.cfg --- quiet
    initrd   /install.amd/initrd.gz
}
"""

ISOLINUX_AUTOINSTALL_ENTRY = """label autoinstall
    menu label ^Debian Autoinstall (Wipes Disk)
    kernel /install.amd/vmlinuz
    append auto=true priority=critical vga=788 initrd=/install.amd/initrd.gz preseed/file=/cdrom/preseed.cfg --- quiet
"""


class DebianBuilder(Builder):
    DISTRO_ID = "debian"
    DISPLAY_NAME = "Debian"
    DEPENDENCIES = ["xorriso", "openssl"]
    DEFAULT_WORKSPACE = "~/debian-autoinstall"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._has_isolinux = False

    def validate_iso(self, iso_path: Path) -> None:
        """
        Verify this is a usable Debian netinst ISO. Accept any ISO with either:
          - /install.amd (the traditional debian-installer kernel/initrd dir)
          - /.disk/info containing "Debian"
        """
        has_install_amd = iso.file_exists_in_iso(iso_path, "/install.amd")
        disk_info = iso.read_iso_text_file(iso_path, "/.disk/info")
        is_debian_by_info = "debian" in disk_info.lower() if disk_info else False

        if has_install_amd or is_debian_by_info:
            if disk_info:
                ui.print_info(f"Detected: {disk_info}")
            self._has_isolinux = iso.file_exists_in_iso(iso_path, "/isolinux")
            return

        contents = iso.list_iso_contents(iso_path, "/")
        preview = ", ".join(contents[:15]) if contents else "(could not list)"
        ui.print_error(
            f"{iso_path} doesn't appear to be a Debian netinst ISO.\n"
            f"  Looked for /install.amd: {'found' if has_install_amd else 'not found'}\n"
            f"  Looked for /.disk/info: {disk_info or 'not found'}\n"
            f"  ISO root contents: {preview}\n"
            f"  Note: this builder targets Debian netinst, not live ISOs.\n"
            f"  Run `build.py inspect <iso>` for full directory listing."
        )

    def bootloader_files(self) -> List[Tuple[str, str]]:
        files = [("/boot/grub/grub.cfg", "boot/grub/grub.cfg")]
        if self._has_isolinux:
            files.append(("/isolinux/menu.cfg", "isolinux/menu.cfg"))
        return files

    def generate_install_files(self, out_dir: Path) -> List[Path]:
        u = self.user_inputs
        ai = self.autoinstall
        identity = ai.get("identity", {}) or {}

        # Build the preseed line by line. PyYAML doesn't help here — preseed
        # has its own non-YAML format. But we're now generating it from
        # validated dict data, not regex-replacing strings.
        preseed_lines = [
            "# Auto-generated Debian preseed",
            "# Generated by isobuilder",
            "",
            f"d-i debian-installer/locale string {u.locale}",
            f"d-i keyboard-configuration/xkb-keymap select {u.keyboard_layout}",
        ]

        if u.keyboard_variant:
            preseed_lines.append(
                f"d-i keyboard-configuration/variant string {u.keyboard_variant}"
            )
        if u.keyboard_toggle:
            preseed_lines.append(
                f"d-i keyboard-configuration/optionscode string {u.keyboard_toggle}"
            )

        preseed_lines.extend([
            f"d-i netcfg/get_hostname string {u.hostname}",
            "d-i netcfg/get_domain string unassigned-domain",
            "d-i mirror/country string manual",
            "d-i mirror/http/hostname string deb.debian.org",
            "d-i mirror/http/directory string /debian",
            "d-i mirror/http/proxy string",
            "d-i passwd/root-login boolean false",
            f"d-i passwd/user-fullname string {u.realname}",
            f"d-i passwd/username string {u.username}",
            f"d-i passwd/user-password-crypted password {u.password_hash or identity.get('password', '')}",
            "d-i clock-setup/utc boolean true",
            f"d-i time/zone string {u.timezone}",
            "",
        ])

        # Disk layout
        if u.disk_layout == 0:
            preseed_lines.extend(self._disk_standard())
        elif u.disk_layout == 1:
            preseed_lines.extend(self._disk_lvm())
        elif u.disk_layout == 2:
            preseed_lines.extend(self._disk_luks(u.crypto_passphrase))

        # Packages: separate tasksel tasks from regular packages
        all_packages = list(ai.get("packages", []) or []) + self.collected_actions.get("packages", [])
        tasksel = [p for p in all_packages if p == "standard"]
        regular = [p for p in all_packages if p != "standard"]
        # Remove duplicates while preserving order
        seen = set()
        regular = [p for p in regular if not (p in seen or seen.add(p))]

        preseed_lines.extend([
            "",
            f"tasksel tasksel/first multiselect {', '.join(tasksel)}",
            f"d-i pkgsel/include string {' '.join(regular)}",
            "d-i pkgsel/upgrade select full-upgrade",
            "popularity-contest popularity-contest/participate boolean false",
            "d-i grub-installer/only_debian boolean true",
            "d-i grub-installer/with_other_os boolean true",
            "d-i grub-installer/bootdev string default",
            "",
        ])

        # Late command: copy post-install script from CD and execute it.
        # No more backslash-continued shell soup.
        late_cmds = self.collected_actions.get("late-commands", [])
        snaps = self.collected_actions.get("snaps", [])
        snap_dicts = []
        for s in snaps:
            if isinstance(s, str) and "|classic" in s:
                snap_dicts.append({"name": s.split("|", 1)[0], "classic": True})
            elif isinstance(s, str):
                snap_dicts.append({"name": s})

        if late_cmds or snap_dicts:
            script_path = out_dir / "post-install.sh"
            postinstall.write_postinstall_script(
                script_path, commands=late_cmds, snaps=snap_dicts
            )
            preseed_lines.extend([
                "d-i preseed/late_command string \\",
                "  cp /cdrom/post-install.sh /target/root/post-install.sh ; \\",
                "  in-target chmod +x /root/post-install.sh ; \\",
                "  in-target /bin/bash /root/post-install.sh ; \\",
                "  in-target rm /root/post-install.sh",
                "",
            ])

        preseed_lines.append("d-i finish-install/reboot_in_progress note")

        preseed_path = out_dir / "preseed.cfg"
        preseed_path.write_text("\n".join(preseed_lines) + "\n")

        result = [preseed_path]
        post_script = out_dir / "post-install.sh"
        if post_script.exists():
            result.append(post_script)
        return result

    @staticmethod
    def _disk_standard() -> List[str]:
        return [
            "d-i partman-auto/method string regular",
            "d-i partman-auto/choose_recipe select atomic",
            "d-i partman-partitioning/confirm_write_new_label boolean true",
            "d-i partman/choose_partition select finish",
            "d-i partman/confirm boolean true",
            "d-i partman/confirm_nooverwrite boolean true",
        ]

    @staticmethod
    def _disk_lvm() -> List[str]:
        return [
            "d-i partman-auto/method string lvm",
            "d-i partman-lvm/device_remove_lvm boolean true",
            "d-i partman-md/device_remove_md boolean true",
            "d-i partman-lvm/confirm boolean true",
            "d-i partman-lvm/confirm_nooverwrite boolean true",
            "d-i partman-auto/choose_recipe select atomic",
            "d-i partman-partitioning/confirm_write_new_label boolean true",
            "d-i partman/choose_partition select finish",
            "d-i partman/confirm boolean true",
            "d-i partman/confirm_nooverwrite boolean true",
        ]

    @staticmethod
    def _disk_luks(passphrase: str) -> List[str]:
        return [
            "d-i partman-auto/method string crypto",
            "d-i partman-lvm/device_remove_lvm boolean true",
            "d-i partman-md/device_remove_md boolean true",
            "d-i partman-lvm/confirm boolean true",
            "d-i partman-lvm/confirm_nooverwrite boolean true",
            "d-i partman-auto-crypto/erase_data boolean false",
            f"d-i partman-crypto/passphrase password {passphrase}",
            f"d-i partman-crypto/passphrase-again password {passphrase}",
            "d-i partman-auto/choose_recipe select atomic",
            "d-i partman-partitioning/confirm_write_new_label boolean true",
            "d-i partman/choose_partition select finish",
            "d-i partman/confirm boolean true",
            "d-i partman/confirm_nooverwrite boolean true",
        ]

    def patch_bootloader(self, extracted: List[Path]) -> List[Path]:
        patched = []
        for f in extracted:
            if f.name == "grub.cfg":
                self._patch_grub(f)
                patched.append(f)
            elif f.name == "menu.cfg":
                self._patch_isolinux(f)
                patched.append(f)
        return patched

    def _patch_grub(self, grub_cfg: Path) -> None:
        content = grub_cfg.read_text()
        if "Debian Autoinstall" in content:
            ui.print_info("grub.cfg already patched, skipping")
            return
        content = content.replace("menuentry ", GRUB_AUTOINSTALL_ENTRY + "menuentry ", 1)
        grub_cfg.write_text(content)
        ui.print_success("Injected autoinstall entry into grub.cfg")

    def _patch_isolinux(self, menu_cfg: Path) -> None:
        content = menu_cfg.read_text()
        if "Debian Autoinstall" in content:
            ui.print_info("isolinux/menu.cfg already patched, skipping")
            return
        # Insert our entry after `include stdmenu.cfg` if present, else at top
        if "include stdmenu.cfg" in content:
            content = content.replace(
                "include stdmenu.cfg",
                "include stdmenu.cfg\n" + ISOLINUX_AUTOINSTALL_ENTRY,
                1,
            )
        else:
            content = ISOLINUX_AUTOINSTALL_ENTRY + content
        menu_cfg.write_text(content)
        ui.print_success("Injected autoinstall entry into isolinux/menu.cfg")

    def iso_file_mappings(
        self, install_files: List[Path], patched_bootloaders: List[Path]
    ) -> List[Tuple[Path, str]]:
        mappings = []
        for f in install_files:
            if f.name == "preseed.cfg":
                mappings.append((f, "/preseed.cfg"))
            elif f.name == "post-install.sh":
                mappings.append((f, "/post-install.sh"))
        for b in patched_bootloaders:
            if b.name == "grub.cfg":
                mappings.append((b, "/boot/grub/grub.cfg"))
            elif b.name == "menu.cfg":
                mappings.append((b, "/isolinux/menu.cfg"))
        return mappings

    def expected_files_in_output(self) -> List[str]:
        files = ["/preseed.cfg", "/boot/grub/grub.cfg"]
        if self._has_isolinux:
            files.append("/isolinux/menu.cfg")
        return files

    def _ask_disk_layout(self) -> None:
        if not ui.UNATTENDED:
            print()
        u = self.user_inputs
        u.disk_layout = ui.ask_choice(
            "Disk partitioning",
            ["Standard (direct wipe)", "LVM", "Encrypted LVM (LUKS)"],
            default=1,
        )
        if u.disk_layout == 2:
            u.crypto_passphrase = ui.ask_password("LUKS encryption passphrase")
            if not u.crypto_passphrase:
                ui.print_error("LUKS encryption requires a passphrase.")
