#!/usr/bin/env python3
"""
Docker Production Installation & Cloudflare Tunnel Setup (Robotic Edition)

Usage:
    # Standard installation (no Cloudflare)
    sudo python3 setup.py

    # Manual Cloudflare Token (tunnel already created in the dashboard)
    sudo python3 setup.py --cloudflare-token <YOUR_TOKEN>

    # FULLY ROBOTIC — creates tunnel, routes, DNS, Access app, and Access
    # policy automatically. Zone IDs are resolved automatically from domain
    # names via the API. The service token is supplied as input (NOT
    # generated by this script — see "Service token" note below).
    sudo python3 setup.py \
        --cf-api-token             "your_api_token" \
        --cf-account-id            "your_account_id" \
        --cf-service-token-id      "xxx.access" \
        --cf-service-token-secret  "xxx" \
        --domain                   "admin.com" \
        --tunnel-name              "prod-server-1" \
        --app-domain               "myordbok.com:http://localhost:8000" \
        --app-domain               "zaideih.com:http://localhost:8080"

    # FORCE OVERWRITE (tunnel with the same name already exists)
    sudo python3 setup.py --force --cf-api-token ... [other args]

    # Dry-run (print what would happen, make no changes)
    sudo python3 setup.py --dry-run --cf-api-token ... [other args]

Notes:
    --app-domain format:  DOMAIN:TARGET
        DOMAIN  — the public hostname (e.g. myordbok.com)
        TARGET  — internal service URL the tunnel forwards to
                  (e.g. http://localhost:8000, https://localhost:443)
    Repeatable — use once per app domain.

    The API token (--cf-api-token) must have:
        Zone:DNS:Edit                    — across all zones being managed
        Account:Cloudflare Tunnel:Edit   — to create / configure the tunnel
        Account:Access: Apps and Policies:Edit
                                         — to create the Access application
                                            and attach the Service Auth policy

    Set resource scope to "All zones" or list each zone explicitly when
    creating the token at Cloudflare → My Profile → API Tokens.

    Service token (--cf-service-token-id / --cf-service-token-secret):
        This script does NOT create the service token. It expects an
        existing token to be supplied and attaches it to the Access policy
        on ssh.<admin-domain>. Create the token once in the Cloudflare
        dashboard (Zero Trust → Access → Service Auth → Service Tokens),
        store the ID and secret in your password manager, and pass them to
        every setup.py run AND to each app's .env (where secrets.py ships
        them to GitHub Actions as CF_SERVICE_TOKEN_ID and
        CF_SERVICE_TOKEN_SECRET).

        Using the same token for setup.py and the deploy pipeline is
        intentional — they're the same actor (the deploy automation) and
        having one credential simplifies rotation. To rotate: delete the
        token in the dashboard, create a new one, update your password
        manager, update each app's .env, run secrets.py --push, then
        re-run setup.py to re-attach the new token to the policy.
"""

import os
import re
import sys
import pwd
import grp
import json
import base64
import secrets
import logging
import argparse
import subprocess
import urllib.request
import urllib.error
from pathlib import Path

# ─── Logging Setup ────────────────────────────────────────────────────────────
LOG_FILE = '/var/log/setup.log'

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)-8s  %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_FILE),
    ]
)
log = logging.getLogger(__name__)


# ─── Argument Parsing ─────────────────────────────────────────────────────────
def parse_args():
    parser = argparse.ArgumentParser(
        description="Docker Production Installation & Robotic Cloudflare Setup",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('--force',    action='store_true', help="Force overwrite of existing tunnels and configs.")
    parser.add_argument('--swap',     type=str, default="2G", help="Swap file size (e.g. 512M, 2G, 4G). Default: 2G")
    parser.add_argument('--dry-run',  action='store_true', help="Print what would happen without making changes.")

    # Manual token path (tunnel already exists in the dashboard)
    parser.add_argument('--cloudflare-token', type=str, default=None,
                        help="Manual Cloudflare Tunnel Token.")

    # Robotic automation — zone IDs are resolved automatically from domain names
    parser.add_argument('--cf-api-token',  type=str,
                        help=("Cloudflare API Token. Needs: Zone:DNS:Edit (all zones), "
                              "Account:Cloudflare Tunnel:Edit, "
                              "Account:Access: Apps and Policies:Edit."))
    parser.add_argument('--cf-account-id', type=str,
                        help="Cloudflare Account ID (found on the dashboard sidebar).")
    parser.add_argument('--cf-service-token-id', type=str,
                        help=("Existing Cloudflare Access Service Token client ID "
                              "(ends in '.access'). Create the token once in the "
                              "Cloudflare dashboard; this script attaches it to the "
                              "Access policy but does NOT generate it."))
    parser.add_argument('--cf-service-token-secret', type=str,
                        help=("Existing Cloudflare Access Service Token client secret. "
                              "Same source as --cf-service-token-id; both are required "
                              "together in robotic mode."))
    parser.add_argument('--domain',        type=str,
                        help="Admin domain (e.g. admin.com). Hosts the admin subdomains "
                             "defined in main()'s admin_subdomains dict.")
    parser.add_argument('--tunnel-name',   type=str, default="prod-server",
                        help="Name for the tunnel in Cloudflare Zero Trust. Default: prod-server")
    parser.add_argument('--app-domain',    type=str, action='append', dest='app_domains',
                        metavar='DOMAIN:TARGET',
                        help=(
                            "App domain and its internal service target. "
                            "Format: domain.com:http://service:port. "
                            "Repeatable — use once per domain. "
                            "Or pass multiple in one flag separated by semicolons: "
                            "'a.com:http://localhost:80;b.com:http://localhost:81'. "
                            "(The semicolon form is useful when called from CI where a "
                            "single secret holds all app domains.)"
                        ))

    # ── rclone / R2 ────────────────────────────────────────────────────────────
    # rclone is always installed. The R2 remote is configured only if BOTH
    # --r2-access-key-id and --r2-secret-access-key are supplied. The endpoint
    # account ID falls back to --cf-account-id if --r2-account-id is omitted.
    parser.add_argument('--r2-access-key-id', type=str,
                        help="Cloudflare R2 Access Key ID. If supplied with the secret, "
                             "writes ~/.config/rclone/rclone.conf with an 'r2' remote.")
    parser.add_argument('--r2-secret-access-key', type=str,
                        help="Cloudflare R2 Secret Access Key. Required together with "
                             "--r2-access-key-id.")
    parser.add_argument('--r2-account-id', type=str,
                        help="Cloudflare Account ID for the R2 endpoint URL. Defaults to "
                             "--cf-account-id when robotic mode is in use.")

    # ── SSH CA trust ────────────────────────────────────────────────────────
    # Trust a Cloudflare Access short-lived SSH CA so cert-based SSH works.
    # Either supply the key directly, or fetch it from the SSH Access app's
    # CA in robotic mode. The CA is never generated here (fetch-only).
    parser.add_argument('--ca-public-key', type=str,
                        help="SSH CA public key line to trust (the 'ssh-... AAAA' "
                             "string). Written to /etc/ssh/ca.pub and wired into "
                             "sshd_config. Takes precedence over --add-ca-public-key.")
    parser.add_argument('--add-ca-public-key', action='store_true',
                        help="Fetch the SSH CA public key from the Access-protected "
                             "SSH app and trust it. Robotic mode only. Aborts if no "
                             "CA has been generated for the app in the dashboard.")

    return parser.parse_args()


# ─── Core Helpers ─────────────────────────────────────────────────────────────
def ensure_root():
    if os.geteuid() != 0:
        log.error("This script must be run as root. Use: sudo python3 setup.py")
        sys.exit(1)

def run_cmd(cmd, hide_output=False, ignore_errors=False, cwd_path=None, dry_run=False):
    display_cmd = cmd if isinstance(cmd, str) else ' '.join(cmd)
    if dry_run:
        print(f"[DRY-RUN] Would execute: {display_cmd}")
        return
    try:
        stdout_target = subprocess.DEVNULL if hide_output else None
        subprocess.run(
            cmd, shell=isinstance(cmd, str), check=True,
            stdout=stdout_target, stderr=subprocess.STDOUT, cwd=cwd_path
        )
        print(f"OK: {display_cmd}")
    except subprocess.CalledProcessError:
        if not ignore_errors:
            log.error(f"Command failed: {display_cmd}")
            sys.exit(1)
        log.warning(f"Ignored error in: {display_cmd}")

def is_tool_installed(name):
    try:
        subprocess.run(['which', name], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except subprocess.CalledProcessError:
        return False

def get_distro_id():
    result = subprocess.run(". /etc/os-release && echo $ID", shell=True, capture_output=True, text=True)
    return result.stdout.strip().lower()

def get_primary_ip():
    result = subprocess.run(
        "ip route get 1.1.1.1 | awk '{print $7; exit}'",
        shell=True, capture_output=True, text=True
    )
    ip = result.stdout.strip()
    if not ip:
        log.error("Could not determine primary server IP address.")
        sys.exit(1)
    return ip

def parse_swap_size_to_mb(size_str):
    m = re.match(r'^(\d+)(G|M)$', size_str.upper())
    if not m:
        raise ValueError(f"Invalid swap size '{size_str}'. Use '512M', '2G', etc.")
    val, unit = int(m.group(1)), m.group(2)
    return val * 1024 if unit == 'G' else val


# ─── Cloudflare API ───────────────────────────────────────────────────────────
def cf_api_request(endpoint, token, method="GET", payload=None):
    """Make an authenticated request to the Cloudflare API."""
    url = f"https://api.cloudflare.com/client/v4{endpoint}"
    data = json.dumps(payload).encode('utf-8') if payload else None
    req = urllib.request.Request(
        url, data=data, method=method,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as e:
        log.error(f"Cloudflare API [{method} {endpoint}] → HTTP {e.code}: {e.read().decode()}")
        raise


def validate_cf_token(api_token):
    """Verify the API token is active before touching anything."""
    print("➜ Validating Cloudflare API token...")
    try:
        result = cf_api_request("/user/tokens/verify", api_token)
        if result.get('result', {}).get('status') == 'active':
            print("✅ Cloudflare API token is valid.")
        else:
            log.error(f"Token is not active: {result}")
            sys.exit(1)
    except Exception:
        log.error("Token validation failed. Check the token value and its permissions.")
        sys.exit(1)


def resolve_zone_id(api_token, domain):
    """
    Look up the Cloudflare Zone ID for a given domain name.
    Tries the exact domain first, then walks up to the apex.
    e.g. sub.example.com → tries sub.example.com, then example.com
    """
    candidates = []
    parts = domain.split('.')
    for i in range(len(parts) - 1):
        candidates.append('.'.join(parts[i:]))

    for candidate in candidates:
        result = cf_api_request(f"/zones?name={candidate}&status=active", api_token)
        zones = result.get('result', [])
        if zones:
            zone_id = zones[0]['id']
            print(f"✅ Zone resolved: {domain} → zone '{candidate}' ({zone_id})")
            return zone_id

    log.error(
        f"Could not resolve a Cloudflare zone for '{domain}'. "
        f"Ensure the domain is added to this Cloudflare account and is Active."
    )
    sys.exit(1)


def dns_upsert(api_token, zone_id, hostname, tunnel_id, force=False):
    """
    Create or update a proxied CNAME record pointing to the tunnel.

    Cloudflare rejects creating a CNAME if an A/AAAA/CNAME with the same
    hostname already exists (error 81053). We fetch ALL record types at
    that hostname and reconcile:
      - existing CNAME      → PUT (update in place)
      - existing A/AAAA     → DELETE then POST (only with --force)
      - nothing             → POST (create)
    """
    payload = {
        "type":    "CNAME",
        "name":    hostname,
        "content": f"{tunnel_id}.cfargotunnel.com",
        "proxied": True,
        "comment": "Auto-managed by setup.py",
    }

    # No type filter — catch A, AAAA, CNAME, anything at this hostname.
    existing = cf_api_request(
        f"/zones/{zone_id}/dns_records?name={hostname}", api_token
    )
    records = existing.get('result', [])

    # Cloudflare only conflicts CNAME with A/AAAA/CNAME; TXT, MX, etc. at
    # the same name are fine and we leave them alone.
    conflicting = [r for r in records if r['type'] in ('A', 'AAAA', 'CNAME')]

    if not conflicting:
        cf_api_request(f"/zones/{zone_id}/dns_records", api_token,
                       method="POST", payload=payload)
        print(f"✅ DNS created:  {hostname}")
        return

    # If there's exactly one record and it's already a CNAME, just update it.
    if len(conflicting) == 1 and conflicting[0]['type'] == 'CNAME':
        record_id = conflicting[0]['id']
        cf_api_request(f"/zones/{zone_id}/dns_records/{record_id}",
                       api_token, method="PUT", payload=payload)
        print(f"✅ DNS updated:  {hostname}")
        return

    # Otherwise A/AAAA records (and possibly a stale CNAME) are blocking us.
    types_found = ', '.join(sorted({r['type'] for r in conflicting}))
    if not force:
        log.error(
            f"DNS conflict for '{hostname}': existing {types_found} record(s) "
            f"would block the new CNAME. Re-run with --force to delete and "
            f"replace them, or remove them manually in the Cloudflare dashboard."
        )
        sys.exit(1)

    print(f"⚠️  --force: deleting {len(conflicting)} conflicting record(s) "
          f"({types_found}) for {hostname}...")
    for r in conflicting:
        cf_api_request(f"/zones/{zone_id}/dns_records/{r['id']}",
                       api_token, method="DELETE")
    cf_api_request(f"/zones/{zone_id}/dns_records", api_token,
                   method="POST", payload=payload)
    print(f"✅ DNS replaced:  {hostname}")


def verify_service_token(api_token, account_id, service_token_id):
    """
    Confirm the supplied service token actually exists in this Cloudflare
    account before we wire it into a policy. The API does not return the
    secret on a list call (the secret is only ever returned at creation
    time), but it does return the client_id, which we can match against.

    Aborts the script if the token is not found — better to fail fast here
    than to create a policy referencing a bogus token and discover the
    mismatch later as 'websocket: bad handshake' from the runner.
    """
    print("➜ Verifying service token exists in this account...")
    result = cf_api_request(
        f"/accounts/{account_id}/access/service_tokens", api_token
    )
    tokens = result.get('result', []) or []
    for t in tokens:
        if t.get('client_id') == service_token_id:
            name = t.get('name', '<unnamed>')
            print(f"✅ Service token verified: '{name}' ({service_token_id})")
            return t.get('id')  # the token's UUID, distinct from client_id
    log.error(
        f"Service token with client_id '{service_token_id}' was not found "
        f"in account {account_id}. Check that:\n"
        f"  1. --cf-service-token-id is correct (it ends in '.access')\n"
        f"  2. --cf-account-id matches the account where the token was created\n"
        f"  3. The token has not been deleted in the Cloudflare dashboard\n"
        f"     (Zero Trust → Access → Service Auth → Service Tokens)."
    )
    sys.exit(1)


def access_app_find_by_hostname(api_token, account_id, hostname):
    """
    Read-only lookup: return the Access application UUID bound to `hostname`,
    or None if no app gates it. Does not create anything — used to resolve an
    app (e.g. the browser-terminal app) that setup.py does not itself manage.
    """
    existing = cf_api_request(
        f"/accounts/{account_id}/access/apps", api_token
    )
    for app in existing.get('result', []) or []:
        if app.get('domain') == hostname:
            return app['id']
    return None


def access_app_upsert(api_token, account_id, hostname, app_name=None,
                      session_duration="24h"):
    """
    Find an existing self-hosted Access application bound to `hostname`,
    or create one. Returns (app_uuid, was_created).

    Idempotency: matching is by domain (the hostname), not by name. This
    matters because the dashboard lets you have multiple apps with the
    same name but different domains, and what we actually care about is
    "is something gating this hostname?". One app per hostname is the
    only sane configuration.
    """
    print(f"➜ Ensuring Access application for '{hostname}'...")
    existing = cf_api_request(
        f"/accounts/{account_id}/access/apps", api_token
    )
    for app in existing.get('result', []) or []:
        # Cloudflare stores the domain with no scheme; compare strictly.
        if app.get('domain') == hostname:
            app_id = app['id']
            print(f"✅ Access app already exists: {hostname} ({app_id})")
            return app_id, False

    payload = {
        "name":              app_name or f"ssh-{hostname}",
        "domain":            hostname,
        "type":              "self_hosted",
        "session_duration":  session_duration,
        # Service tokens authenticate non-interactively; no IdP login UI.
        # Leaving allowed_idps unset accepts any configured IdP for human
        # access, which we don't need here but doesn't hurt — the policy
        # is what actually gates entry.
    }
    result = cf_api_request(
        f"/accounts/{account_id}/access/apps", api_token,
        method="POST", payload=payload
    )
    app_id = result['result']['id']
    print(f"✅ Access app created: {hostname} ({app_id})")
    return app_id, True


def access_policy_ensure(api_token, account_id, app_id, service_token_uuid,
                         policy_name="Service Auth — deploy pipeline"):
    """
    Ensure the given Access app has a Service Auth policy that includes
    the given service token. Idempotent: if a policy with the right
    decision and include rule already exists, leave it alone; otherwise
    create one.

    NOTE on identifiers: the Access policy API references service tokens
    by their internal UUID (the 'id' field), NOT by their client_id (the
    'xxxx.access' value supplied on the command line). The two are
    different identifiers for the same token. service_token_uuid here is
    the UUID returned by verify_service_token().

    The 'decision' field for service-token-only policies is "non_identity"
    in the Cloudflare API — that's the API-side name for what the
    dashboard labels "Service Auth". An "allow" policy will not work for
    service tokens; it routes through the IdP login flow and produces
    'websocket: bad handshake' for non-interactive clients.
    """
    print(f"➜ Ensuring Service Auth policy on app {app_id}...")
    existing = cf_api_request(
        f"/accounts/{account_id}/access/apps/{app_id}/policies", api_token
    )
    for policy in existing.get('result', []) or []:
        if policy.get('decision') != 'non_identity':
            continue
        # Look for a service_token include rule referencing our token.
        # The matching field is 'token_id', and its value is the UUID.
        includes = policy.get('include', []) or []
        for rule in includes:
            st = rule.get('service_token') or {}
            if st.get('token_id') == service_token_uuid:
                print(f"✅ Service Auth policy already in place "
                      f"(policy id: {policy['id']}).")
                return policy['id'], False

    # Compute the next available precedence number. Cloudflare requires
    # precedences to be unique within an app; hard-coding 1 collides with
    # any policy left over from a partial run or manual experimentation.
    used_precedences = [
        p.get('precedence', 0) for p in (existing.get('result') or [])
        if isinstance(p.get('precedence'), int)
    ]
    next_precedence = max(used_precedences) + 1 if used_precedences else 1

    payload = {
        "name":      policy_name,
        "decision":  "non_identity",
        "include":   [{"service_token": {"token_id": service_token_uuid}}],
        "exclude":   [],
        "require":   [],
        "precedence": next_precedence,
    }
    result = cf_api_request(
        f"/accounts/{account_id}/access/apps/{app_id}/policies", api_token,
        method="POST", payload=payload
    )
    policy_id = result['result']['id']
    print(f"✅ Service Auth policy created (policy id: {policy_id}).")
    return policy_id, True


def cf_fetch_ssh_ca_public_key(api_token, account_id, app_id):
    """
    Fetch the short-lived SSH CA public key for a specific Access application
    (the 'ecdsa-sha2-nistp256 AAAA... open-ssh-ca@cloudflareaccess.org' line a
    server puts in /etc/ssh/ca.pub).

    This is the per-application (Certificate type: Application) CA — the kind
    generated in the dashboard by picking the app in the Application dropdown,
    which the browser-rendered SSH terminal uses. It is distinct from the
    account-wide Access-for-Infrastructure CA (gateway_ca); a single account
    can have both, so the right one is selected by app_id.

    Fetch-only — same stance as the service token: the CA is durable shared
    trust state. Every server that trusts it accepts certs signed by it, so
    regenerating it would silently break SSH on sibling servers. Generating
    is a deliberate dashboard action, never a side effect of a setup.py run.

    Aborts loudly if no CA has been generated for the app, pointing at the
    dashboard step rather than surfacing a raw HTTP error.
    """
    print(f"➜ Fetching SSH CA public key for Access app {app_id}...")
    try:
        result = cf_api_request(
            f"/accounts/{account_id}/access/apps/{app_id}/ca", api_token
        )
    except urllib.error.HTTPError:
        log.error(
            "No short-lived certificate CA exists for this Access app.\n"
            "Generate it once in the Cloudflare dashboard:\n"
            "  Zero Trust → Access controls → Service credentials → SSH\n"
            "  → Add a certificate → in the Application dropdown choose the\n"
            "    SSH/terminal app → Generate certificate.\n"
            "Then re-run with --add-ca-public-key. The CA is created once and "
            "reused across rebuilds — this script never generates it."
        )
        sys.exit(1)

    public_key = (result.get('result') or {}).get('public_key')
    if not public_key:
        log.error(
            "Cloudflare returned no public_key for this Access app's CA. "
            "Confirm a short-lived certificate CA (Certificate type: "
            "Application) exists for the SSH app in the dashboard."
        )
        sys.exit(1)
    print("✅ SSH CA public key fetched.")
    return public_key


def automate_cloudflare(api_token, account_id, admin_domain, tunnel_name,
                        ingress_rules, admin_subdomains, app_domain_map,
                        service_token_id, force=False, add_ca_public_key=False):
    """
    Full robotic Cloudflare setup:
      1. Validate API token
      2. Verify the supplied service token exists in this account
      3. Resolve all zone IDs automatically from domain names
      4. Create (or recreate) the tunnel
      5. Push ingress routing rules
      6. Upsert all DNS CNAME records
      7. For every admin_subdomains entry with protect_with_access_app=True:
         create (or reuse) the Access application and attach a Service Auth
         policy referencing the supplied service token

    admin_subdomains is a dict keyed by subdomain name. Each value is a dict:
      {
        "service": <tunnel ingress target, e.g. "tcp://localhost:22">,
        "protect_with_access_app": <optional bool — default False>,
        "app_name": <optional Access app display name>,
      }

    To add a new internal proxy: append one entry to admin_subdomains in
    main(). DNS, ingress, and (optionally) Access app are wired up
    automatically. To rename an existing subdomain: change the key. DNS,
    ingress, Access app, and post-install summary all follow.

    Returns: (tunnel_token, tunnel_id, access_app_id, ssh_ca_public_key)
      access_app_id is the ID of the *last* Access app created, or None if
      no admin_subdomains entry had protect_with_access_app=True.
      ssh_ca_public_key is the per-app SSH CA public key fetched from the
      ca_cert-flagged app (only when add_ca_public_key=True), else None.
    """
    print("\n🤖 Initiating Robotic Cloudflare Setup...")
    validate_cf_token(api_token)
    # The Access policy API references service tokens by their internal UUID,
    # not their client_id (the .access value). verify_service_token returns
    # the UUID — capture it here for use in access_policy_ensure() below.
    service_token_uuid = verify_service_token(api_token, account_id, service_token_id)

    # ── Resolve all zone IDs upfront before creating anything ─────────────────
    print("\n➜ Resolving zone IDs from domain names...")
    admin_zone_id = resolve_zone_id(api_token, admin_domain)

    # Each app domain resolves its own zone independently
    app_zone_map = {}  # { "myordbok.com": {"zone_id": "...", "target": "http://localhost:8000"} }
    for domain_name, target in app_domain_map.items():
        zone_id = resolve_zone_id(api_token, domain_name)
        app_zone_map[domain_name] = {"zone_id": zone_id, "target": target}

    # ── Tunnel: check / delete / create ───────────────────────────────────────
    print(f"\n➜ Checking for existing tunnel '{tunnel_name}'...")
    existing = cf_api_request(f"/accounts/{account_id}/cfd_tunnel?name={tunnel_name}", api_token)

    if existing['result']:
        if not force:
            log.error(f"Tunnel '{tunnel_name}' already exists. Use --force to delete and recreate it.")
            sys.exit(1)
        old_id = existing['result'][0]['id']
        print(f"⚠️  --force: removing existing tunnel '{tunnel_name}' (ID: {old_id})...")
        # Drain connections first, then delete
        cf_api_request(f"/accounts/{account_id}/cfd_tunnel/{old_id}/connections",
                       api_token, method="DELETE")
        cf_api_request(f"/accounts/{account_id}/cfd_tunnel/{old_id}",
                       api_token, method="DELETE")
        print("✅ Old tunnel removed.")

    print(f"➜ Creating tunnel '{tunnel_name}'...")
    secret_b64 = base64.b64encode(secrets.token_bytes(32)).decode()
    tunnel_res = cf_api_request(
        f"/accounts/{account_id}/cfd_tunnel", api_token, method="POST",
        payload={"name": tunnel_name, "tunnel_secret": secret_b64}
    )
    tunnel_id    = tunnel_res['result']['id']
    tunnel_token = tunnel_res['result'].get('token')
    if not tunnel_token:
        log.error("Cloudflare did not return a tunnel token. Cannot continue.")
        sys.exit(1)
    print(f"✅ Tunnel created (ID: {tunnel_id})")

    # ── Ingress routing rules ──────────────────────────────────────────────────
    print("➜ Configuring ingress routing rules...")
    cf_api_request(
        f"/accounts/{account_id}/cfd_tunnel/{tunnel_id}/configurations",
        api_token, method="PUT",
        payload={"config": {"ingress": ingress_rules}}
    )
    print("✅ Ingress rules applied.")

    # ── DNS records ────────────────────────────────────────────────────────────
    print("\n➜ Creating / updating DNS CNAME records...")

    # Every admin subdomain gets a DNS record in the admin zone. The
    # subdomain dict drives this — add a key, get a DNS record.
    for sub in admin_subdomains:
        hostname = f"{sub}.{admin_domain}"
        dns_upsert(api_token, admin_zone_id, hostname, tunnel_id, force=force)

    # App domains → each their own resolved zone
    for domain_name, config in app_zone_map.items():
        dns_upsert(api_token, config["zone_id"], domain_name, tunnel_id, force=force)

    # ── Access application + Service Auth policy ──────────────────────────────
    # Driven entirely off the admin_subdomains dict: any entry that sets
    # protect_with_access_app=True gets an Access app on its hostname plus
    # a Service Auth policy that references the supplied service token.
    #
    # This is the layer that makes 'cloudflared access ssh' from GitHub
    # Actions actually authenticate. Without it, the WebSocket handshake to
    # Cloudflare's edge fails with 'websocket: bad handshake' because there
    # is no policy to evaluate the service token against.
    access_app_id = None
    ssh_ca_public_key = None
    for sub, spec in admin_subdomains.items():
        if not spec.get("protect_with_access_app"):
            continue
        hostname = f"{sub}.{admin_domain}"
        display_name = spec.get("app_name") or f"{sub.upper()} — {admin_domain}"
        print(f"\n➜ Configuring Cloudflare Access for {hostname}...")
        app_id, _created = access_app_upsert(
            api_token, account_id, hostname, app_name=display_name,
        )
        access_policy_ensure(
            api_token, account_id, app_id, service_token_uuid,
        )
        access_app_id = app_id  # Returned to caller; last one wins if multiple

    # The browser-terminal SSH CA is a per-application (Certificate type:
    # Application) CA, bound to a specific Access app — the entry flagged
    # ca_cert in admin_subdomains (the terminal app). That app is not
    # necessarily Access-protected by this script, so resolve its ID by
    # hostname read-only rather than assuming the loop above created it.
    if add_ca_public_key:
        ca_hosts = [
            f"{sub}.{admin_domain}"
            for sub, spec in admin_subdomains.items()
            if spec.get("ca_cert")
        ]
        if not ca_hosts:
            log.error(
                "--add-ca-public-key was given but no admin_subdomains entry "
                "is flagged ca_cert. Mark the entry whose Access app holds the "
                "short-lived certificate (the terminal app), or pass the key "
                "directly with --ca-public-key."
            )
            sys.exit(1)
        if len(ca_hosts) > 1:
            log.error(
                f"Multiple admin_subdomains entries are flagged ca_cert "
                f"({', '.join(ca_hosts)}). Exactly one app owns the SSH CA."
            )
            sys.exit(1)
        ca_host = ca_hosts[0]
        ca_app_id = access_app_find_by_hostname(api_token, account_id, ca_host)
        if not ca_app_id:
            log.error(
                f"No Access application is bound to {ca_host}. Create the "
                f"browser-terminal Access app in the dashboard first, then "
                f"generate its short-lived certificate."
            )
            sys.exit(1)
        ssh_ca_public_key = cf_fetch_ssh_ca_public_key(
            api_token, account_id, ca_app_id
        )

    print("\n🤖 Robotic Cloudflare Setup Complete.")
    return tunnel_token, tunnel_id, access_app_id, ssh_ca_public_key


# ─── System Setup ─────────────────────────────────────────────────────────────
def ensure_python_alias():
    if is_tool_installed('python'):
        return
    print("🔗 Linking 'python3' → 'python'...")
    try:
        os.symlink('/usr/bin/python3', '/usr/bin/python')
        print("✅ Symlink created.")
    except OSError as e:
        log.warning(f"Could not create python symlink: {e}")


def setup_swap(size="2G", force=False, dry_run=False):
    print(f"Checking swap (target: {size})...")
    parse_swap_size_to_mb(size)
    swap_file = Path('/swapfile')

    with open('/proc/swaps') as f:
        swap_active = str(swap_file) in f.read()

    if swap_active and not force:
        print("Skip: swap already active.")
        return

    if swap_active and force:
        run_cmd(['swapoff', str(swap_file)], ignore_errors=True, dry_run=dry_run)
        if not dry_run:
            swap_file.unlink(missing_ok=True)

    run_cmd(['fallocate', '-l', size, str(swap_file)], ignore_errors=True, dry_run=dry_run)

    if not dry_run and not swap_file.exists():
        run_cmd(['dd', 'if=/dev/zero', f'of={swap_file}', 'bs=1M',
                 f'count={parse_swap_size_to_mb(size)}'], hide_output=True)

    if not dry_run:
        os.chmod(str(swap_file), 0o600)

    run_cmd(['mkswap', str(swap_file)], dry_run=dry_run)
    run_cmd(['swapon', str(swap_file)], dry_run=dry_run)

    if not dry_run:
        with open('/etc/fstab', 'r') as f:
            if '/swapfile' not in f.read():
                with open('/etc/fstab', 'a') as fa:
                    fa.write('\n/swapfile swap swap defaults 0 0\n')
    print(f"✅ Swap ({size}) enabled.")


def setup_security(dry_run=False):
    print("Setting up security and tooling...")
    run_cmd(['apt-get', 'update', '-qq'], dry_run=dry_run)
    # jq is required by check_local_vm_runner in deploy.yml
    # python3-boto3 is required by the Django app for GCS/S3 bucket access
    run_cmd(['apt-get', 'install', '-y', 'fail2ban', 'unattended-upgrades', 'jq', 'python3-boto3'],
            hide_output=True, dry_run=dry_run)
    run_cmd(['systemctl', 'enable', '--now', 'fail2ban'], dry_run=dry_run)
    run_cmd("echo 'unattended-upgrades unattended-upgrades/enable_auto_updates boolean true' "
            "| debconf-set-selections", hide_output=True, dry_run=dry_run)
    run_cmd(['dpkg-reconfigure', '-f', 'noninteractive', 'unattended-upgrades'],
            hide_output=True, dry_run=dry_run)
    print("✅ Security tooling installed.")


def setup_ssh_ca(public_key, dry_run=False):
    """
    Trust an SSH CA public key for certificate-based auth: write it to
    /etc/ssh/ca.pub and point sshd at it via TrustedUserCAKeys, ensuring
    PubkeyAuthentication is on.

    Idempotent and conflict-safe:
      - ca.pub: append the key only if that exact line is absent.
      - sshd_config: keyed on directive NAME, not the whole line. If the
        directive is already set to the wanted value, leave it. If it is set
        to a DIFFERENT value, abort loudly rather than append a second,
        conflicting directive (sshd's last-wins would mask the operator's
        intent silently).
      - sshd is reloaded only when something actually changed.
    """
    if not public_key:
        return
    print("Trusting SSH CA public key...")

    ca_path = Path('/etc/ssh/ca.pub')
    sshd_config = Path('/etc/ssh/sshd_config')
    wanted = {
        'TrustedUserCAKeys': str(ca_path),
        'PubkeyAuthentication': 'yes',
    }
    key_line = public_key.strip()

    if dry_run:
        print(f"[DRY-RUN] Would write {ca_path} and ensure in {sshd_config}: "
              + ", ".join(f"{k} {v}" for k, v in wanted.items()))
        return

    # ── ca.pub ────────────────────────────────────────────────────────────
    ca_path.parent.mkdir(parents=True, exist_ok=True)
    existing_keys = ca_path.read_text().splitlines() if ca_path.exists() else []
    ca_changed = key_line not in [l.strip() for l in existing_keys]
    if ca_changed:
        with open(ca_path, 'a') as f:
            if existing_keys and not existing_keys[-1].endswith('\n'):
                f.write('\n')
            f.write(key_line + '\n')
        print(f"✅ CA public key added to {ca_path}.")
    else:
        print(f"Skip: CA public key already present in {ca_path}.")
    os.chmod(ca_path, 0o644)

    # ── sshd_config ─────────────────────────────────────────────────────────
    lines = sshd_config.read_text().splitlines() if sshd_config.exists() else []
    config_changed = False
    for directive, value in wanted.items():
        # Match an active (uncommented) directive by name.
        idx = None
        current = None
        for i, line in enumerate(lines):
            m = re.match(rf'^\s*{directive}\s+(\S.*)$', line)
            if m:
                idx, current = i, m.group(1).strip()
                break
        if current is None:
            lines.append(f"{directive} {value}")
            config_changed = True
            print(f"✅ {directive} {value} added to {sshd_config}.")
        elif current == value:
            print(f"Skip: {directive} already set to '{value}'.")
        else:
            log.error(
                f"{directive} is already set to '{current}' in {sshd_config}, "
                f"not '{value}'. Refusing to append a conflicting directive. "
                f"Resolve the existing value by hand, then re-run."
            )
            sys.exit(1)

    if config_changed:
        sshd_config.write_text('\n'.join(lines) + '\n')

    # Reload sshd only if either file changed. reload (not restart) keeps the
    # current SSH session alive while picking up the new trust.
    if ca_changed or config_changed:
        run_cmd(['sshd', '-t'])  # validate before reload; aborts on bad config
        run_cmd(['systemctl', 'reload', 'ssh'], ignore_errors=True)
        run_cmd(['systemctl', 'reload', 'sshd'], ignore_errors=True)
        print("✅ sshd reloaded — CA trust active.")
    else:
        print("Skip: SSH CA trust already in place; no reload needed.")


def setup_firewall(dry_run=False):
    """
    UFW rules:
      22  — SSH (open initially; close after Cloudflare Tunnel SSH is verified)
      80  — HTTP (landing-page nginx; also kept open for direct debugging)
      443 — HTTPS (not used by anything on the host currently — Cloudflare
            terminates TLS at the edge and the tunnel forwards plain HTTP to
            localhost:80; kept open as a no-op escape valve)
    """
    print("Configuring UFW firewall...")
    run_cmd(['apt-get', 'install', '-y', 'ufw'], hide_output=True, dry_run=dry_run)
    run_cmd(['ufw', 'default', 'deny',  'incoming'], dry_run=dry_run)
    run_cmd(['ufw', 'default', 'allow', 'outgoing'], dry_run=dry_run)
    run_cmd(['ufw', 'allow', 'ssh'],     dry_run=dry_run)
    run_cmd(['ufw', 'allow', '80/tcp'],  dry_run=dry_run)
    run_cmd(['ufw', 'allow', '443/tcp'], dry_run=dry_run)
    run_cmd(['ufw', '--force', 'enable'], dry_run=dry_run)
    print("✅ UFW configured.")


def setup_directories(directories, dry_run=False):
    print("Setting up application directories...")
    current_user = os.environ.get('SUDO_USER') or os.environ.get('USER') or 'root'
    for d in directories:
        dir_path = Path(d['path'])
        owner    = current_user if d.get('owner') == 'current-user' else d.get('owner', 'root')
        perms    = d.get('permissions', 0o755)
        if dry_run:
            print(f"[DRY-RUN] Would create {dir_path} (owner: {owner}, mode: {oct(perms)})")
            continue
        dir_path.mkdir(parents=True, exist_ok=True)
        try:
            if str(owner).isdigit():
                uid = int(owner)
                os.chown(dir_path, uid, uid)
            else:
                info = pwd.getpwnam(owner)
                os.chown(dir_path, info.pw_uid, info.pw_gid)
            os.chmod(dir_path, perms)
            print(f"OK: {dir_path}  (owner: {owner}, mode: {oct(perms)})")
        except Exception as e:
            log.warning(f"Could not set permissions on {dir_path}: {e}")


def setup_rclone(access_key_id=None, secret_access_key=None, account_id=None,
                 force=False, dry_run=False):
    """
    Install rclone (always) and write an R2 remote config (only if credentials
    are supplied).

    Why install always: rclone is useful on the box regardless — copying
    between R2 buckets, ad-hoc backups, restore drills — and it's a single
    static binary with no Python deps. Cost is ~50 MB and one apt-free
    install. The official curl-installer is preferred over the apt package,
    which lags releases by months on Debian/Ubuntu.

    Config is written to ~/.config/rclone/rclone.conf of the invoking user
    (SUDO_USER if available, else $USER, else root). Mode 600 — it contains
    secrets. The 'r2' remote name matches the convention used by the project's
    backup tooling.
    """
    print("Setting up rclone...")

    if not is_tool_installed('rclone') or force:
        if dry_run:
            print("[DRY-RUN] Would install rclone via official installer.")
        else:
            # The official script pulls the latest stable release as a deb on
            # Debian/Ubuntu (zip on others). Quieter and more current than apt.
            run_cmd("curl -fsSL https://rclone.org/install.sh | bash",
                    hide_output=True)
            print("✅ rclone installed.")
    else:
        print("Skip: rclone is already installed.")

    # Write the R2 remote config only if BOTH key and secret are present.
    # Partial credentials are a footgun — fail loudly.
    if not (access_key_id or secret_access_key):
        print("ℹ️  No R2 credentials supplied — skipping rclone.conf. "
              "Pass --r2-access-key-id and --r2-secret-access-key to configure.")
        return
    if not (access_key_id and secret_access_key):
        log.error(
            "rclone R2 config needs BOTH --r2-access-key-id AND "
            "--r2-secret-access-key (got only one)."
        )
        sys.exit(1)
    if not account_id:
        log.error(
            "rclone R2 config needs an account ID for the endpoint URL. "
            "Pass --r2-account-id, or run in robotic mode where --cf-account-id "
            "is reused automatically."
        )
        sys.exit(1)

    # Resolve who owns ~/.config/rclone/rclone.conf. SUDO_USER is the human
    # who ran `sudo python3 setup.py`; falling back to USER covers the case
    # where the script runs as root directly (rare for this codebase).
    target_user = os.environ.get('SUDO_USER') or os.environ.get('USER') or 'root'
    try:
        pw = pwd.getpwnam(target_user)
    except KeyError:
        log.error(f"User '{target_user}' not found on this system.")
        sys.exit(1)

    home = Path(pw.pw_dir)
    conf_dir  = home / '.config' / 'rclone'
    conf_path = conf_dir / 'rclone.conf'
    endpoint  = f"https://{account_id}.r2.cloudflarestorage.com"

    rclone_conf = (
        "[r2]\n"
        "type = s3\n"
        "provider = Cloudflare\n"
        f"access_key_id = {access_key_id}\n"
        f"secret_access_key = {secret_access_key}\n"
        f"endpoint = {endpoint}\n"
        "region = auto\n"
        "acl = private\n"
    )

    if dry_run:
        print(f"[DRY-RUN] Would write {conf_path} (owner: {target_user}, mode: 600).")
        print(f"[DRY-RUN]   endpoint = {endpoint}")
        return

    # Idempotency: if a remote called [r2] already exists and --force was not
    # passed, leave it alone. Avoids clobbering a manually-tuned config on
    # re-runs of setup.py.
    if conf_path.exists() and not force:
        existing = conf_path.read_text()
        if '[r2]' in existing:
            print(f"Skip: {conf_path} already contains an [r2] remote. "
                  f"Pass --force to overwrite.")
            return

    conf_dir.mkdir(parents=True, exist_ok=True)
    conf_path.write_text(rclone_conf)
    os.chown(conf_dir,  pw.pw_uid, pw.pw_gid)
    os.chown(conf_path, pw.pw_uid, pw.pw_gid)
    os.chmod(conf_dir,  0o700)
    os.chmod(conf_path, 0o600)
    print(f"✅ rclone R2 remote written to {conf_path} (600, owner: {target_user}).")


def setup_docker(force=False, dry_run=False):
    if not is_tool_installed('docker') or force:
        print("Installing Docker Engine...")
        distro_id = get_distro_id()
        run_cmd(['apt-get', 'update', '-qq'], dry_run=dry_run)
        run_cmd(['apt-get', 'install', '-y', 'ca-certificates', 'curl', 'gnupg', 'lsb-release'],
                hide_output=True, dry_run=dry_run)
        run_cmd(f"curl -fsSL https://download.docker.com/linux/{distro_id}/gpg "
                f"| gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes", dry_run=dry_run)
        if not dry_run:
            os.chmod('/etc/apt/keyrings/docker.gpg', 0o644)
        arch     = subprocess.run(['dpkg', '--print-architecture'],
                                  capture_output=True, text=True).stdout.strip()
        codename = subprocess.run(". /etc/os-release && echo $VERSION_CODENAME",
                                  shell=True, capture_output=True, text=True).stdout.strip()
        repo = (f"deb [arch={arch} signed-by=/etc/apt/keyrings/docker.gpg] "
                f"https://download.docker.com/linux/{distro_id} {codename} stable\n")
        if not dry_run:
            with open('/etc/apt/sources.list.d/docker.list', 'w') as f:
                f.write(repo)
        run_cmd(['apt-get', 'update', '-qq'], dry_run=dry_run)
        run_cmd(['apt-get', 'install', '-y',
                 'docker-ce', 'docker-ce-cli', 'containerd.io',
                 'docker-buildx-plugin', 'docker-compose-plugin'],
                hide_output=True, dry_run=dry_run)
    else:
        print("Skip: Docker is already installed.")

    run_cmd(['systemctl', 'enable', '--now', 'docker'], dry_run=dry_run)

    # Log rotation — without this Docker JSON logs grow unbounded
    docker_etc  = Path('/etc/docker')
    daemon_path = docker_etc / 'daemon.json'
    if not daemon_path.exists() or force:
        daemon_cfg = {"log-driver": "json-file", "log-opts": {"max-size": "50m", "max-file": "5"}}
        if not dry_run:
            docker_etc.mkdir(parents=True, exist_ok=True)
            with open(daemon_path, 'w') as f:
                json.dump(daemon_cfg, f, indent=4)
            run_cmd(['systemctl', 'restart', 'docker'])
            print("✅ Docker daemon.json written (log rotation enabled).")
        else:
            print(f"[DRY-RUN] Would write {daemon_path} with log rotation config.")

    # Sanity-check the compose plugin
    if not dry_run:
        result = subprocess.run(['docker', 'compose', 'version'], capture_output=True, text=True)
        if result.returncode != 0:
            log.error("docker compose plugin not functional after installation.")
            sys.exit(1)
        print(f"✅ {result.stdout.strip()}")

    # Add the invoking user to the 'docker' group so they can run `docker`
    # without sudo. This is post-install hygiene — every Docker CLI command
    # in the rest of this script is run as root (we're under sudo), so this
    # step doesn't affect setup.py itself; it's purely for the operator's
    # interactive use afterwards.
    #
    # usermod -aG is idempotent (re-adding a user to a group they're already
    # in is a no-op), so this is safe on every re-run. We skip if the
    # resolved user is root (root is implicitly in all groups; adding root
    # to 'docker' is pointless).
    #
    # newgrp is intentionally NOT called here — newgrp only affects the shell
    # that runs it, and a shell spawned by Python exits immediately. The user
    # has to run `newgrp docker` themselves (or log out and back in) to
    # activate the group in their current terminal session. We print a hint
    # to that effect, but only when the user wasn't already a member — no
    # point repeating the hint on every re-run.
    target_user = os.environ.get('SUDO_USER') or os.environ.get('USER') or 'root'
    if target_user == 'root':
        pass  # root doesn't need to be added to docker group
    else:
        already_member = False
        try:
            docker_group = grp.getgrnam('docker')
            already_member = target_user in docker_group.gr_mem
        except KeyError:
            # The 'docker' group doesn't exist yet — the Docker package
            # creates it on install, so this only happens in dry-run mode
            # before the install has run.
            pass

        if dry_run:
            print(f"[DRY-RUN] Would add user '{target_user}' to the 'docker' group.")
        elif already_member:
            print(f"Skip: '{target_user}' is already in the 'docker' group.")
        else:
            run_cmd(['usermod', '-aG', 'docker', target_user])
            print(f"✅ Added '{target_user}' to the 'docker' group.")
            print(f"   To use docker without sudo in your current shell, run:")
            print(f"     newgrp docker")
            print(f"   Or log out and back in. New shells will pick it up automatically.")


def setup_docker_swarm(dry_run=False):
    """
    Initialises Docker Swarm if not already active, then ensures the required
    overlay network exists. Networks must be created after Swarm is active
    because overlay networks require Swarm mode.

    Networks created:
      gateway   — Shared overlay network. Not required for the
                  tunnel-to-app path: the tunnel reaches apps via
                  localhost:<port> directly. Created here because app stack
                  deploys may declare it as an external network, and
                  creating it once is cheaper than re-creating it on each
                  deploy. Harmless if unused.
    """
    print("Checking Docker Swarm...")
    if dry_run:
        print("[DRY-RUN] Would initialise Docker Swarm if inactive.")
        print("[DRY-RUN] Would create overlay network: gateway")
        return

    result = subprocess.run(
        ['docker', 'info', '--format', '{{.Swarm.LocalNodeState}}'],
        capture_output=True, text=True
    )
    if result.stdout.strip() == 'inactive':
        run_cmd(['docker', 'swarm', 'init', '--advertise-addr', get_primary_ip()])
        print("✅ Docker Swarm initialised.")
    else:
        print("Skip: Docker Swarm is already active.")

    # Create the shared overlay network — idempotent, safe to re-run
    network = "gateway"
    check = subprocess.run(
        ['docker', 'network', 'inspect', network],
        capture_output=True
    )
    if check.returncode != 0:
        run_cmd([
            'docker', 'network', 'create',
            '--driver', 'overlay',
            '--attachable',
            network
        ])
        print(f"✅ Overlay network '{network}' created.")
    else:
        print(f"Skip: network '{network}' already exists.")


def setup_cloudflare_tunnel(cf_token=None, force=False, dry_run=False):
    """
    Deploy the Cloudflare Tunnel container as its own compose stack at
    /opt/cloudflare-tunnel/. The tunnel runs with network_mode: host so
    'localhost' inside the container is the Docker host itself — which is
    how every ingress rule (ssh.<domain>, app domains, the landing page on
    port 80) reaches its target without container names or bridge IPs.

    Only runs if cf_token is supplied (which means robotic mode actually
    completed the Cloudflare API call and got a tunnel token back, OR the
    operator passed --cloudflare-token manually). In dry-run mode this is
    typically a no-op because automate_cloudflare() doesn't return a real
    token in dry-run.
    """
    print("Setting up Cloudflare Tunnel...")
    if dry_run:
        print("[DRY-RUN] Would create /opt/cloudflare-tunnel/, write .env (600) "
              "and docker-compose.yml, then bring the tunnel up.")
        return
    if not cf_token:
        print("Skip: no Cloudflare tunnel token available — pass either the "
              "robotic flags (--cf-api-token + friends) or --cloudflare-token.")
        return

    tunnel_dir = Path('/opt/cloudflare-tunnel')
    tunnel_dir.mkdir(parents=True, exist_ok=True)

    # Token goes in .env, not in the compose YAML — keeps it out of
    # process listings and source control.
    env_path = tunnel_dir / '.env'
    env_path.write_text(f"TUNNEL_TOKEN={cf_token}\n")
    os.chmod(env_path, 0o600)
    print(f"✅ Tunnel token written to {env_path} (600).")

    compose = (
        "version: '3.8'\n"
        "services:\n"
        "  tunnel:\n"
        "    image: cloudflare/cloudflared:latest\n"
        "    container_name: cloudflare-tunnel\n"
        "    restart: unless-stopped\n"
        "    env_file: .env\n"
        "    command: tunnel --no-autoupdate run\n"
        "    # network_mode: host gives the tunnel direct access to the host\n"
        "    # network stack. 'localhost' inside this container == the Docker\n"
        "    # host. Every ingress rule uses localhost as a result — no\n"
        "    # container names, no bridge networks, no host-gateway magic.\n"
        "    network_mode: host\n"
    )

    compose_file = tunnel_dir / 'docker-compose.yml'
    if compose_file.exists() and force:
        print("⚠️  --force: bringing tunnel down before reapplying...")
        run_cmd(['docker', 'compose', 'down'], cwd_path=tunnel_dir)

    compose_file.write_text(compose)
    run_cmd(['docker', 'compose', 'up', '-d'], cwd_path=tunnel_dir)
    print("✅ Cloudflare Tunnel is running.")


def setup_landing(force=False, dry_run=False):
    """
    Deploy a vanilla nginx container at /opt/landing/ that serves
    /opt/bucket/html on port 80. This is the catch-all landing page for any
    request that reaches localhost:80 — including everything the Cloudflare
    tunnel's catch-all ingress rule sends here (i.e. anything not matched by
    a more specific tunnel route).

    The config is deliberately minimal — one server block, one root, one
    try_files. The landing layer only serves static files: TLS terminates
    at the Cloudflare edge and proxying happens at the tunnel via localhost
    ports, so nothing here needs to do more than hand back files.

    The container:
      - Binds 0.0.0.0:80 (so the tunnel can reach it on localhost:80, and
        also so the public IP can reach it directly if needed for debugging).
      - Mounts /opt/bucket/html read-only as its document root. Drop files
        into that host directory to update the page; nginx serves from the
        bind mount on every request, no reload needed.
      - Mounts nginx.conf read-write — vanilla nginx doesn't mutate it, but
        we leave write access open for future updates of the image that
        might need to (e.g. an nginx variant that runs a startup script
        which sed-edits its own conf).
      - try_files $uri $uri/ /index.html falls back to the SPA shell for
        client-side-routed paths.
    """
    print("Setting up landing-page nginx...")
    landing_dir = Path('/opt/landing')

    if dry_run:
        print(f"[DRY-RUN] Would create {landing_dir}, write nginx.conf + "
              f"docker-compose.yml, then bring up nginx:alpine on :80.")
        return

    landing_dir.mkdir(parents=True, exist_ok=True)
    conf_dir = landing_dir / 'conf'
    conf_dir.mkdir(parents=True, exist_ok=True)

    nginx_conf = conf_dir / 'nginx.conf'
    nginx_conf.write_text(
        '# Vanilla nginx server block for the catch-all landing page.\n'
        '# Serves /opt/bucket/html (bind-mounted into the container at\n'
        '# /usr/share/nginx/html) with SPA fallback to /index.html.\n'
        '\n'
        'server {\n'
        '    listen 80 default_server;\n'
        '    listen [::]:80 default_server;\n'
        '    server_name _;\n'
        '\n'
        '    root /usr/share/nginx/html;\n'
        '    index index.html;\n'
        '\n'
        '    # Standard SPA fallback. Concrete files (style.css, script.js,\n'
        '    # favicon.ico, etc.) resolve via $uri and serve as static files.\n'
        '    # Unknown paths fall back to /index.html so client-side routing\n'
        '    # can take over. =404 prevents infinite loops if the SPA shell\n'
        '    # itself is missing.\n'
        '    location / {\n'
        '        try_files $uri $uri/ /index.html =404;\n'
        '    }\n'
        '\n'
        '    # Sensible logging — same files nginx:alpine uses by default,\n'
        '    # which docker logs surfaces via stdout/stderr redirects in the\n'
        '    # base image.\n'
        '    access_log /var/log/nginx/access.log;\n'
        '    error_log  /var/log/nginx/error.log warn;\n'
        '}\n'
    )
    print(f"✅ Landing nginx config written to {nginx_conf}.")

    compose = (
        "version: '3.8'\n"
        "services:\n"
        "  landing:\n"
        "    image: nginx:alpine\n"
        "    container_name: landing\n"
        "    restart: unless-stopped\n"
        "    ports:\n"
        "      - '80:80'\n"
        "    volumes:\n"
        "      # SPA files. ro so a typo in the SPA can't break nginx and\n"
        "      # a compromised nginx can't write back to the host.\n"
        "      - /opt/bucket/html:/usr/share/nginx/html:ro\n"
        "      # The server block. NOT ro — vanilla nginx doesn't mutate\n"
        "      # this, but future image versions might (e.g. envsubst at\n"
        "      # startup). Cost of leaving writable is zero.\n"
        "      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf\n"
    )

    compose_file = landing_dir / 'docker-compose.yml'
    if compose_file.exists() and force:
        print("⚠️  --force: bringing landing nginx down before reapplying...")
        run_cmd(['docker', 'compose', 'down'], cwd_path=landing_dir)

    compose_file.write_text(compose)

    # Seed a placeholder index.html only if /opt/bucket/html is empty —
    # never clobber operator-supplied content on re-runs.
    html_dir = Path('/opt/bucket/html')
    if html_dir.exists() and not any(html_dir.iterdir()):
        placeholder = html_dir / 'index.html'
        placeholder.write_text(
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "<head><meta charset=\"utf-8\"><title>Not configured</title></head>\n"
            "<body style=\"font-family:system-ui;max-width:40rem;margin:4rem auto;"
            "padding:0 1rem;color:#333\">\n"
            "<h1>Nothing here yet</h1>\n"
            "<p>This server is online but no site is configured at this hostname. "
            "Drop an <code>index.html</code> into <code>/opt/bucket/html</code> "
            "to replace this page.</p>\n"
            "</body></html>\n"
        )
        print(f"✅ Seeded placeholder {placeholder}.")

    # --force-recreate on the landing service so a re-run with config
    # changes applies them. The landing stack only has one service so the
    # whole stack is recreated — no concern about bouncing a tunnel here,
    # since the tunnel lives in /opt/cloudflare-tunnel/ now.
    run_cmd(['docker', 'compose', 'up', '-d', '--force-recreate', 'landing'],
            cwd_path=landing_dir)
    print("✅ Landing-page nginx is running on :80.")


def print_post_install_summary(robotic_setup=False, tunnel_id=None,
                               admin_domain=None, admin_subdomains=None,
                               app_domains=None, access_app_id=None):
    print("\n" + "=" * 62)
    print("✅  INSTALLATION COMPLETE")
    print("=" * 62)

    if robotic_setup:
        # Render every admin subdomain from the dict — rename a key and it
        # follows here automatically. The 'protected' label highlights which
        # one(s) have the Cloudflare Access policy that the deploy pipeline
        # authenticates against.
        admin_lines = []
        access_protected_hostname = None
        for sub, spec in (admin_subdomains or {}).items():
            host = f"{sub}.{admin_domain or '?'}"
            target = spec.get("service", "?")
            if spec.get("protect_with_access_app"):
                admin_lines.append(f"    {host}  →  {target}  (Access-protected)")
                access_protected_hostname = host
            else:
                admin_lines.append(f"    {host}  →  {target}")
        admin_block = '\n'.join(admin_lines) or "    (none)"

        app_list = '\n'.join(
            f"    {d}  →  {v['target']}" for d, v in (app_domains or {}).items()
        ) or "    (none)"

        # The service-token note only makes sense if some subdomain is
        # actually Access-protected. If none are, skip that paragraph.
        service_auth_note = ""
        if access_protected_hostname:
            service_auth_note = (
                f"\n   The service token you supplied is now attached to a "
                f"Service Auth policy\n"
                f"   on {access_protected_hostname}. The same token ID and "
                f"secret should already\n"
                f"   be in each app repo's .env as:\n"
                f"       CF_SERVICE_TOKEN_ID\n"
                f"       CF_SERVICE_TOKEN_SECRET\n"
                f"   so the deploy pipeline (deploy.yml) can SSH through the tunnel.\n"
            )

        print(f"""
🤖 ROBOTIC CLOUDFLARE SETUP COMPLETE
   Tunnel ID     : {tunnel_id or 'see Cloudflare dashboard'}
   Access app ID : {access_app_id or 'see Cloudflare dashboard'}
   Admin routes:
{admin_block}
   App routes:
{app_list}

   Anything not matched by a specific tunnel ingress rule falls through
   the catch-all to localhost:80, where the landing-page nginx serves
   /opt/bucket/html. Drop your SPA into that directory to replace the
   placeholder.
{service_auth_note}
   HTTP→HTTPS and WWW→root redirects must be configured in the
   Cloudflare dashboard (Rules → Redirect Rules) — not handled here.
""")
    else:
        print("""
   Landing-page nginx is running on :80, serving /opt/bucket/html.
   Test with:  curl -H "Host: nothing.invalid" http://localhost/
""")

    print("""\
NEXT STEPS
  1. Drop your SPA build output into /opt/bucket/html/ to replace the
     placeholder landing page. No restart needed — nginx reads from the
     bind mount on every request.
  2. Register the GitHub Actions self-hosted runner:
     https://github.com/<org>/<repo>/settings/actions/runners/new
  3. In each app repo, ensure .env has the deploy values populated, then
     run secrets.py --push to ship them to GitHub Actions.
  4. Test Cloudflare Tunnel SSH before closing port 22:
     ssh -o ProxyCommand="cloudflared access ssh --hostname %h" \\
         root@ssh.<your-domain>
  5. Once SSH tunnel is verified:  sudo ufw delete allow ssh
""")
    print("=" * 62)


# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    args = parse_args()
    ensure_root()
    ensure_python_alias()

    # ══════════════════════════════════════════════════════════════
    # CONFIGURATION BLOCK
    # Edit these values to match the deployment. No other changes
    # needed for typical setups.
    # ══════════════════════════════════════════════════════════════

    system_directories = [
        # Shared persistent storage used by both apps
        {"path": "/opt/bucket",       "owner": "current-user", "permissions": 0o755},
        {"path": "/opt/bucket/storage","owner": "current-user", "permissions": 0o755},
        {"path": "/opt/bucket/media", "owner": "current-user", "permissions": 0o755},
        # Document root for the landing-page nginx — bind-mounted read-only
        # into the container by setup_landing().
        {"path": "/opt/bucket/html",  "owner": "current-user", "permissions": 0o755},
        # Per-app deployment directories (deploy.yml writes compose + .env here)
        {"path": "/opt/myordbok",     "owner": "current-user", "permissions": 0o700},
        {"path": "/opt/zaideih",      "owner": "current-user", "permissions": 0o700},
        # Django media uploads
        {"path": "/opt/django/media", "owner": "current-user", "permissions": 0o755},
        # MySQL data — uid 999 is the mysql user inside the container
        {"path": "/opt/mysql/data",   "owner": "999",          "permissions": 0o755},
    ]

    # ── Admin subdomains ──────────────────────────────────────────────────────
    # Admin domain for the subdomains below. Falls back to 'admin.com' if
    # --domain is not supplied (non-robotic mode).
    admin_domain = args.domain or "admin.com"

    # The dict below is the SINGLE source of truth for every admin subdomain.
    # The script derives DNS records, tunnel ingress rules, Access apps, and
    # the post-install summary from it. To add a new internal proxy: append
    # one entry. To rename: change the key. Everything follows.
    #
    # Each entry:
    #   "service" (required) — the tunnel ingress target. Anything the
    #     cloudflared --no-autoupdate run process can route to. Common
    #     schemes: 'http://localhost:<port>', 'https://localhost:<port>',
    #     'tcp://localhost:22'. SSH uses tcp:// (not ssh://): remotely
    #     managed tunnels — configured via the API as this script does —
    #     route SSH as a raw TCP service. The ssh:// scheme belongs to the
    #     older local-config-file model and is silently ignored here.
    #     localhost works because cloudflared runs with network_mode: host
    #     (see setup_cloudflare_tunnel).
    #   "protect_with_access_app" (optional, default False) — when True,
    #     setup.py creates a Cloudflare Access application on this hostname
    #     and attaches a Service Auth policy referencing the supplied
    #     service token. This is what lets 'cloudflared access tcp' from
    #     the GitHub Actions deploy pipeline authenticate without a human
    #     browser login. Required for SSH; meaningless for HTTP routes
    #     unless you also want them gated by the same service token.
    #   "app_name" (optional) — display name shown in the Cloudflare
    #     dashboard for the Access app. Defaults to "<SUB> — <admin_domain>".
    #
    # Examples of adding entries (uncomment / adapt as needed):
    #   "grafana":   {"service": "http://localhost:3000"},
    #   "portainer": {"service": "https://localhost:9443"},
    admin_subdomains = {
        "ssh": {
            "service": "tcp://localhost:22",
            "protect_with_access_app": True,
            "app_name": f"SSH — {admin_domain}",
        },
        # Browser-rendered SSH terminal. This entry intentionally creates
        # only the DNS record and tunnel ingress rule (ssh:// scheme, which
        # the browser-render flow expects). It does NOT set
        # protect_with_access_app, so setup.py creates no Access app, policy,
        # or service-token wiring for it.
        #
        # The remaining setup is done once in the Cloudflare dashboard,
        # deliberately kept out of setup.py: the short-lived-certificate
        # method it relies on is labelled legacy ("not recommended for new
        # deployments"), so automating sshd CA-trust edits against it would
        # build server-modifying code on a moving target. The dashboard
        # steps, one time:
        #   1. Zero Trust → Access → Applications: create a self_hosted app
        #      on terminal.<admin_domain>. Set Browser rendering to "SSH".
        #   2. Add an Allow policy (Service Auth / Bypass are unsupported for
        #      browser-rendered apps) with an email rule for the operator.
        #   3. Zero Trust → Access → Service Auth → SSH: generate the
        #      short-lived-cert CA for this app, copy its public key.
        #   4. On the server: trust that CA in sshd_config
        #      (TrustedUserCAKeys), ensuring the operator's email prefix
        #      matches a Unix username, then reload ssh.
        # The browser terminal needs these sshd KEX algorithms; add if
        # absent: curve25519-sha256, curve25519-sha256@libssh.org,
        # ecdh-sha2-nistp256/384/521.
        "terminal": {
            "service": "ssh://localhost:22",
            # Holds the browser-terminal short-lived certificate (Application
            # CA). --add-ca-public-key fetches this app's CA and trusts it.
            "ca_cert": True,
        },
    }

    # ══════════════════════════════════════════════════════════════
    # END CONFIGURATION BLOCK
    # ══════════════════════════════════════════════════════════════

    # ── Parse --app-domain flags ───────────────────────────────────────────────
    # Each --app-domain flag value contains one OR MORE entries.
    #   Single:  --app-domain "myordbok.com:http://localhost:8000"
    #   Multi:   --app-domain "a.com:http://localhost:80;b.com:http://localhost:81"
    # The semicolon form lets a single CI secret hold every app domain. By
    # hand, repeating the flag is more readable. Both produce the same map.
    #
    # split(':', 1) caps at one split so 'http://localhost:8000' is not split
    # at the scheme colon.
    app_domain_map = {}  # { "myordbok.com": "http://localhost:8000" }
    if args.app_domains:
        # Flatten: every flag value may itself contain ;-separated entries
        flat_entries = []
        for flag_value in args.app_domains:
            for entry in flag_value.split(';'):
                entry = entry.strip()
                if entry:
                    flat_entries.append(entry)

        for entry in flat_entries:
            parts = entry.split(':', 1)
            if len(parts) != 2 or not parts[1].startswith('http'):
                log.error(
                    f"Invalid --app-domain value: '{entry}'\n"
                    f"Expected format:  domain.com:http://service:port\n"
                    f"Example:          myordbok.com:http://localhost:8000\n"
                    f"Multiple in one flag are separated by ';'."
                )
                sys.exit(1)
            domain_name, target = parts[0].strip(), parts[1].strip()
            app_domain_map[domain_name] = target

    # ── Build ingress rules from the admin_subdomains dict + --app-domain ─────
    # The tunnel container runs with network_mode: host so localhost inside
    # the container IS the Docker host. All services reachable via localhost —
    # no container names, bridge IPs, or host-gateway special hostnames needed.
    ingress_rules = []
    for sub, spec in admin_subdomains.items():
        ingress_rules.append({
            "hostname": f"{sub}.{admin_domain}",
            "service":  spec["service"],
        })
    for domain_name, target in app_domain_map.items():
        ingress_rules.append({"hostname": domain_name, "service": target})
    # Mandatory catch-all — anything not matched above falls through here.
    # localhost:80 is the landing-page nginx (see setup_landing).
    ingress_rules.append({"service": "http://localhost:80"})

    # ── Validate robotic mode argument completeness ────────────────────────────
    robotic_args = [
        args.cf_api_token,
        args.cf_account_id,
        args.domain,
        args.cf_service_token_id,
        args.cf_service_token_secret,
    ]
    if any(robotic_args) and not all(robotic_args):
        log.error(
            "Robotic mode requires all of:\n"
            "  --cf-api-token\n"
            "  --cf-account-id\n"
            "  --domain\n"
            "  --cf-service-token-id\n"
            "  --cf-service-token-secret\n"
            "Pass them all, or pass none (and use --cloudflare-token instead "
            "for a manual-tunnel setup)."
        )
        sys.exit(1)

    # Sanity-check the service token ID format up front. Cloudflare service
    # token client IDs always end in '.access' — catching a malformed value
    # here is much friendlier than a 404 from the API later.
    if args.cf_service_token_id and not args.cf_service_token_id.endswith('.access'):
        log.error(
            f"--cf-service-token-id should end in '.access' "
            f"(got: {args.cf_service_token_id!r}). "
            f"Make sure you copied the Client ID, not the token name or UUID."
        )
        sys.exit(1)

    # ── Run Cloudflare automation or fall back to manual token ─────────────────
    token          = args.cloudflare_token
    robotic_setup  = False
    tunnel_id      = None
    access_app_id  = None
    ssh_ca_public_key = None

    if all(robotic_args):
        if args.dry_run:
            print("[DRY-RUN] Would call Cloudflare API to create tunnel, ingress rules, and DNS.")
            print(f"[DRY-RUN] Admin zone for '{admin_domain}' would be resolved automatically.")
            for d in app_domain_map:
                print(f"[DRY-RUN] App zone for '{d}' would be resolved automatically.")
            print(f"[DRY-RUN] Would verify service token '{args.cf_service_token_id}' "
                  f"in account '{args.cf_account_id}'.")
            print(f"[DRY-RUN] Would upsert Access app for ssh.{admin_domain} and "
                  f"attach a Service Auth policy referencing the service token.")
        else:
            token, tunnel_id, access_app_id, ssh_ca_public_key = automate_cloudflare(
                api_token         = args.cf_api_token,
                account_id        = args.cf_account_id,
                admin_domain      = admin_domain,
                tunnel_name       = args.tunnel_name,
                ingress_rules     = ingress_rules,
                admin_subdomains  = admin_subdomains,
                app_domain_map    = app_domain_map,
                service_token_id  = args.cf_service_token_id,
                force             = args.force,
                add_ca_public_key = args.add_ca_public_key,
            )
            robotic_setup = True

    # ── System setup ───────────────────────────────────────────────────────────
    setup_swap(size=args.swap, force=args.force, dry_run=args.dry_run)
    setup_security(dry_run=args.dry_run)
    # --ca-public-key (explicit) wins over the fetched key; either may be None.
    setup_ssh_ca(args.ca_public_key or ssh_ca_public_key, dry_run=args.dry_run)
    setup_firewall(dry_run=args.dry_run)
    setup_directories(system_directories, dry_run=args.dry_run)
    # rclone install is unconditional; R2 remote is only configured if
    # credentials were supplied. Account ID falls back to --cf-account-id
    # when robotic mode is in use, so a single account ID covers both.
    setup_rclone(
        access_key_id     = args.r2_access_key_id,
        secret_access_key = args.r2_secret_access_key,
        account_id        = args.r2_account_id or args.cf_account_id,
        force             = args.force,
        dry_run           = args.dry_run,
    )
    setup_docker(force=args.force, dry_run=args.dry_run)
    setup_docker_swarm(dry_run=args.dry_run)
    setup_cloudflare_tunnel(cf_token=token, force=args.force, dry_run=args.dry_run)
    setup_landing(force=args.force, dry_run=args.dry_run)

    # Build the app_domains dict for the summary (include resolved targets)
    summary_app_domains = {
        d: {"target": t} for d, t in app_domain_map.items()
    } if robotic_setup else {}

    print_post_install_summary(
        robotic_setup    = robotic_setup,
        tunnel_id        = tunnel_id,
        admin_domain     = admin_domain,
        admin_subdomains = admin_subdomains,
        app_domains      = summary_app_domains,
        access_app_id    = access_app_id,
    )


if __name__ == "__main__":
    main()