"""
Generate post-install shell scripts.

Previously, late-commands were embedded into the preseed/user-data via
backslash-continued shell quoting — fragile and impossible to debug. Now we
write a real shell script to a separate file on the ISO, and the preseed
just runs it.

Benefits:
  - You can read the script with `cat` to see exactly what will run
  - Quoting bugs are caught at script generation, not at install time
  - Failed commands are individually logged with `set -x`
  - You can SSH into a half-installed box and re-run the script manually
"""

from pathlib import Path
from typing import List

POSTINSTALL_HEADER = """#!/bin/bash
# Auto-generated post-install script.
# Generated by isobuilder. Do not edit by hand — regenerate from preset.

set -u
# Fail loud, not silent. We continue past individual command failures so a
# single broken package doesn't strand the install, but every failure is
# logged with its exit code to /var/log/isobuilder-postinstall.log.

LOG=/var/log/isobuilder-postinstall.log
mkdir -p /var/log
exec > >(tee -a "$LOG") 2>&1
echo "=== isobuilder post-install started at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="

run() {
    echo ">>> $*"
    if "$@"; then
        echo "    OK"
    else
        rc=$?
        echo "    FAILED (exit $rc)" >&2
    fi
}

run_shell() {
    # For complex commands with pipes, redirects, etc.
    echo ">>> $1"
    if bash -c "$1"; then
        echo "    OK"
    else
        rc=$?
        echo "    FAILED (exit $rc)" >&2
    fi
}

"""

POSTINSTALL_FOOTER = """
echo "=== isobuilder post-install finished at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
"""


def build_postinstall_script(
    commands: List[str],
    snaps: List[dict] = None,
) -> str:
    """
    Render a post-install shell script from a list of commands and snaps.

    Each command runs through `run_shell`, which logs the command, its
    outcome, and exit code. Failures are logged but don't abort the script —
    a single broken command shouldn't strand the entire install.
    """
    snaps = snaps or []
    lines = [POSTINSTALL_HEADER]

    if snaps:
        lines.append("# Snaps")
        lines.append('run systemctl start snapd.socket || true')
        for s in snaps:
            name = s.get("name") if isinstance(s, dict) else s
            classic = ""
            if isinstance(s, dict) and s.get("classic"):
                classic = " --classic"
            lines.append(f'run snap install {name}{classic}')
        lines.append("")

    if commands:
        lines.append("# Late commands")
        for cmd in commands:
            # Strip cloud-init's `curtin in-target --` prefix if present —
            # we're already running inside the target, no need.
            cleaned = cmd.replace("curtin in-target -- ", "").strip()
            if not cleaned:
                continue
            # Use run_shell to handle pipes, redirects, &&, etc.
            # Single-quote escape for embedding in the bash script
            escaped = cleaned.replace("'", "'\\''")
            lines.append(f"run_shell '{escaped}'")
        lines.append("")

    lines.append(POSTINSTALL_FOOTER)
    return "\n".join(lines)


def write_postinstall_script(
    path: Path,
    commands: List[str],
    snaps: List[dict] = None,
) -> Path:
    """Write a post-install script to disk and make it executable."""
    import shutil
    import subprocess

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = build_postinstall_script(commands, snaps)
    with open(path, "w") as f:
        f.write(content)
    path.chmod(0o755)

    # Bash syntax check — catches generation bugs before we ship the script
    # onto the ISO. If bash is unavailable (rare), skip silently.
    if shutil.which("bash"):
        result = subprocess.run(
            ["bash", "-n", str(path)],
            capture_output=True, text=True, check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"Generated post-install script has bash syntax error:\n"
                f"{result.stderr}\n\n"
                f"Script saved at: {path}\n"
                f"This is a bug in isobuilder, not your preset. Please report."
            )

    return path