title: "Lethil"
description: "Infrastructure, tooling, and self-hosted systems."
lang: "en"

baseurl: ""
url: "https://khensolomon.github.io"

permalink: pretty
markdown: kramdown

sass:
  sass_dir: _sass
  style: expanded

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - .jekyll-cache

collections_dir: .
collections:
  docs: { output: true, permalink: /docs/:name/ }
  python: { output: true, permalink: /python/:name/ }
  linux: { output: true, permalink: /linux/:name/ }
  server: { output: true, permalink: /server/:name/ }
  plex: { output: true, permalink: /plex/:name/ }
  note: { output: true, permalink: /note/:name/ }
  quote: { output: true, permalink: /quote/:name/ }
  sql: { output: true, permalink: /sql/:name/ }

defaults:
  - scope: { path: "", type: "docs" }
    values: { layout: "docs", section: "docs" }
  - scope: { path: "", type: "python" }
    values: { layout: "docs", section: "python" }
  - scope: { path: "", type: "linux" }
    values: { layout: "docs", section: "linux" }
  - scope: { path: "", type: "server" }
    values: { layout: "docs", section: "server" }
  - scope: { path: "", type: "plex" }
    values: { layout: "docs", section: "plex" }
  - scope: { path: "", type: "note" }
    values: { layout: "docs", section: "note" }
  - scope: { path: "", type: "quote" }
    values: { layout: "docs", section: "quote" }
  - scope: { path: "", type: "sql" }
    values: { layout: "docs", section: "sql" }
